name: Release AWS Profile Switcher
on:
  push:
    branches: [ main ]
    tags:
      - "*"
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Go 1.20.5
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: Build
        run: |
          go get -d -v
          go build -v .

      -      
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_GITHUB_TOKEN }}
